### ISSUE TITLE
请问下配置iptable的时候报错是什么原因呢

### ISSUE THREAD

**Issue by YangQuan666** [iloahz/asus-router-stock-firmware-clash#2]
运行命令：`iptables -t nat -A clash -p tcp --dport 7890 -j RETURN`
报错显示：iptables: No chain/target/match by that name

**Comment by iloahz** [comment]
可能是还没有创建这个chain，`/usr/sbin/iptables -t nat -N CLASH` 这条命令是创建一个名为`CLASH`的chain

**Comment by YangQuan666** [comment]
多谢大佬，搞定了
